### ISSUE TITLE
Extended TiledMap support

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/braingdx#30]
![tiled-logo](http://www.mapeditor.org/img/tiled-logo-white.png)
This feature offers extended support for the [TiledMap](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/maps/tiled/TiledMap.html) implementation. It will integrate smoothly with **braingdx** and provides easy configuration.

## Motivation

The `TiledMap` implementation [provided by libgdx](https://github.com/libgdx/libgdx/wiki/Tile-maps) gives general support for using tiled maps. However, when creating games for game jams it is always time-consuming to write the render pipeline for tiled maps and levels all over again. Also having an **API** which provides easy support for collision detection and object handling is one goal of this story.

## Rendering and z-indexing

One particular problem when implementing this story is in which order to render layers and objects. The rendering itself can not be implemented as an own `RenderLayer` since `GameObject` instances should get rendered before or after a certain layer. In addition `GameObject` instances for layers should not be taken into account for collision detection or world deletion. This can be achieved by treating a `MapLayer` as a game object and assigning own renderers for each layer individually. Afterwards **braingdx** needs to calculate the **z-index** for every `GameObject` to decide in which order to render:
```
index = (layerIndex + 1) * rowCount + yPosition
```
**Explanation:** first of all the z-index needs to be higher on a higher layer, regardless of how big the index is in the layer beneath. This can be ensured by multiplying the current index of the layer with the total number of rows. Afterwards the current `yPosition` of the `GameObject` is added.

## Tasks

- [x] implement active/inactive mode for `GameObject`
- [x] implement z-index calculator and z-index assignment for `GameObject` instances
- [x] implement `MapLayerRenderManager` (generating individual ids for render layers and assigning own renderers to it)
- [x] implement `MapLayerRenderer`
- [x] implement collision cache
- [x] implement `TiledMapManager` to load tiled maps and populate the world with defined objects
- [x] implement `TiledMapAPI` to provide access like collision checks, indexed-based field checks (neighbours, layers)
- [x] implement support for moving game objects between layers at runtime (configurable via `TiledMapConfiguration`)
- [x] introduce a `TiledMapConfiguration` in order to define how to parse attributes like collision, game objects, items etc.
- [x] Implement collision detection
