### ISSUE TITLE
Setup Maven Central repository

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/braingdx#9]
Setup this repository for Maven Central according to [these requirements](https://central.sonatype.org/pages/requirements.html) and [OSSRH Guide](https://central.sonatype.org/pages/ossrh-guide.html).

The relevant request ticket [can be found here](https://issues.sonatype.org/browse/OSSRH-40921).

## Tasks

- [x] request braingdx repository on Sonartype
- [x] change pom.xml to deploy to Maven Central
- [x] setup GPG signing within TravisCI. ([example](https://github.com/bitbrain/jpersis/tree/master/deployment))
- [x] integrate Javadoc deployment into pipeline ([example](https://github.com/bitbrain/jpersis/tree/master/deployment))
- [x] update README.md to use official Maven Central Nexus
- [x] promote staged artifacts into Maven Central (Release)

**Comment by bitbrain** [comment]
Almost there. Currently failing to promote artifacts for release: https://issues.sonatype.org/browse/OSSRH-40921?focusedCommentId=492133&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-492133

**Comment by bitbrain** [comment]
You can now obtain **braingdx** via [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22braingdx-core%22).

I will close this ticket as soon the Javadoc deployment is successful.
